import streamlit as st


def render_user_guide():
    with st.expander("How to use **rxn-explore** server?", expanded=False, icon="❓"):
        st.markdown(
            """
        This app allows you to easily browse and analyze the **molecules** and **synthetic pathways** produced by the
        generative model of GenProSyn. It serves as an interface between organic chemists and molecular data files 
        generated by the model.
        
        ---
        ### Layout:
    
        The core app functionalities are divided between three important pages:
            
        - 💾 _Load Data_ (current page) - to **upload data** file to server
        - 👁 _Browse Molecules_ - to **visualize molecules** and synthetic pathways
        - ⭐ _Favourites_ - summary of molecules previously **marked as favourite** in browser
            
        To navigate between pages, use the navigation menu located at the very top
        of the left sidebar.
        
        ---
        ### Usage:
        
        1. Start by uploading your `.csv` file. On the current page (_Load Data_) locate the data
        upload widget. Select the `.csv` file from your local storage and send it to the server by 
        clicking the _Upload data_ button.
        
            **If the dataset is loaded correctly, two things will change in Session Status window:**
            - The message box background will change color from **blue** -> **green**.
            - The **Dataset loaded** message will appear in the box, followed by the name of the uploaded file."""
        )

        st.info(
            "**Session Status** is a message displayed on the left sidebar, just the below navigation menu. "
            "It signals whether a dataset has been successfully loaded to the server or not.",
            icon="ℹ️",
        )

        st.markdown("""
        2. Files uploaded to the server should contain at least two columns: `molecule` and `path`.
        Size of the input files must not exceed 100MB. Widget located at the bottom of *Load Data* page allows you to save 
        the uploaded file to to library (which is just server storage), making your data easy to access in future sessions
        by you or any other user. The maximum number of datasets to be stored in library is 100.

        3. **Navigate to _Browse Molecules_** page to visualize molecules present in the dataset. Each molecule is displayed
        together with its synthetic pathway and some supporting descriptors. The molecules of the data file are accessed 
        by their index (position in the dataset) - the indexes start from 0. You can either advance through the dataset
        by increasing/decreasing molecule index with two arrow buttons of the widget, or input the desired index with
        your keyboard. Promising molecules can be marked as _favourite_ by clicking the button with a star icon. 
        This will allow you to easily come back to them later.
    
        4. **Navigate to _Favourites_** page to view the molecules you have marked as favourite as a summary in table format.
        Clicking the eye icon in a row corresponding to chosen molecule moves you to the corresponding _Browse Molecules_ page, 
        where the synthetic pathway is rendered. You can also use the button located below the data table to download all
        current favourites as a .csv file.
        """)
        st.warning(
            """**WARNING:** All your session data, including your list of favourite molecules, is always lost\
            when you close the browser tab or exit the session otherwise!""",
            icon="⚠️",
        )
        st.info(
            "The only data which is retained on server between sessions and can be accessed directly after login "
            "are the **datasets** which have been added to **library** 📚.",
            icon="ℹ️",
        )

        st.caption(
            "Keep in mind that this app is still under development. "
            "You are welcome to report bugs and request new features.",
            text_alignment="center",
        )
